-- The mount lists for Useful Extras and QuickMountGather by EVmaker

SJMount_staticMountList = {}

-- -----------------------------------------------------------------------------
-- Ground Mounts (SJMOUNT_CONSTS.MOUNTLEVELS.MOUNTLEVEL1)
-- -----------------------------------------------------------------------------
---
SJMount_staticMountList[43688] = "GROUND" -- Amani War Bear
SJMount_staticMountList[16056] = "GROUND" -- Ancient Frostsaber (feat of strength)
SJMount_staticMountList[66906] = "GROUND" -- Argent Charger
SJMount_staticMountList[67466] = "GROUND" -- Argent Warhorse
SJMount_staticMountList[66907] = "GROUND" -- Argent Warhorse
SJMount_staticMountList[60114] = "GROUND" -- Armored Brown Bear
SJMount_staticMountList[60116] = "GROUND" -- Armored Brown Bear
SJMount_staticMountList[51412] = "GROUND" -- Big Battle Bear
SJMount_staticMountList[58983] = "GROUND" -- Big Blizzard Bear
SJMount_staticMountList[35020] = "GROUND" -- Blue Hawkstrider
SJMount_staticMountList[10969] = "GROUND" -- Blue Mechanostrider
SJMount_staticMountList[33630] = "GROUND" -- Blue Mechanostrider
SJMount_staticMountList[22719] = "GROUND" -- Black Battlestrider
SJMount_staticMountList[35022] = "GROUND" -- Black Hawkstrider
SJMount_staticMountList[16055] = "GROUND" -- Black Nightsaber (feat of strength)
SJMount_staticMountList[59572] = "GROUND" -- Black Polar Bear
SJMount_staticMountList[26656] = "GROUND" -- Black Qiraji Battle Tank
SJMount_staticMountList[17461] = "GROUND" -- Black Ram
SJMount_staticMountList[64977] = "GROUND" -- Black Skeletal Horse
SJMount_staticMountList[470]   = "GROUND" -- Black Stallion
SJMount_staticMountList[60118] = "GROUND" -- Black War Bear
SJMount_staticMountList[60119] = "GROUND" -- Black War Bear
SJMount_staticMountList[48027] = "GROUND" -- Black War Elekk
SJMount_staticMountList[22718] = "GROUND" -- Black War Kodo
SJMount_staticMountList[59785] = "GROUND" -- Black War Mammoth
SJMount_staticMountList[59788] = "GROUND" -- Black War Mammoth
SJMount_staticMountList[22720] = "GROUND" -- Black War Ram
SJMount_staticMountList[22721] = "GROUND" -- Black War Raptor
SJMount_staticMountList[22717] = "GROUND" -- Black War Steed
SJMount_staticMountList[22723] = "GROUND" -- Black War Tiger
SJMount_staticMountList[22724] = "GROUND" -- Black War Wolf
SJMount_staticMountList[578]   = "GROUND" -- Black Wolf
SJMount_staticMountList[64658] = "GROUND" -- Black Wolf
SJMount_staticMountList[6897]  = "GROUND" -- Blue Ram
SJMount_staticMountList[17463] = "GROUND" -- Blue Skeletal Horse
SJMount_staticMountList[50869] = "GROUND" -- Brewfest Kodo
SJMount_staticMountList[49378] = "GROUND" -- Brewfest Riding Kodo
SJMount_staticMountList[43899] = "GROUND" -- Brewfest Ram
SJMount_staticMountList[50870] = "GROUND" -- Brewfest Ram
SJMount_staticMountList[34406] = "GROUND" -- Brown Elekk
SJMount_staticMountList[458]   = "GROUND" -- Brown Horse
SJMount_staticMountList[18990] = "GROUND" -- Brown Kodo
SJMount_staticMountList[59573] = "GROUND" -- Brown Polar Bear
SJMount_staticMountList[6899]  = "GROUND" -- Brown Ram
SJMount_staticMountList[88748] = "GROUND" -- Brown Riding Camel
SJMount_staticMountList[17464] = "GROUND" -- Brown Skeletal Horse
SJMount_staticMountList[6654]  = "GROUND" -- Brown Wolf
SJMount_staticMountList[75614] = "GROUND" -- Celestial Steed (variable)
SJMount_staticMountList[6648]  = "GROUND" -- Chestnut Mare
SJMount_staticMountList[39315] = "GROUND" -- Cobalt Riding Talbuk
SJMount_staticMountList[34896] = "GROUND" -- Cobalt War Talbuk
SJMount_staticMountList[73313] = "GROUND" -- Crimson Deathcharger
SJMount_staticMountList[68188] = "GROUND" -- Crusader's Black Warhorse
SJMount_staticMountList[68187] = "GROUND" -- Crusader's White Warhorse
SJMount_staticMountList[39316] = "GROUND" -- Dark Riding Talbuk
SJMount_staticMountList[34790] = "GROUND" -- Dark War Talbuk
SJMount_staticMountList[63635] = "GROUND" -- Darkspear Raptor (new Argent troll)
SJMount_staticMountList[63637] = "GROUND" -- Darnassian Nightsaber (new Argent nightelf)
SJMount_staticMountList[48778] = "GROUND" -- Deathcharger
SJMount_staticMountList[6653]  = "GROUND" -- Dire Wolf
SJMount_staticMountList[8395]  = "GROUND" -- Emerald Raptor
SJMount_staticMountList[63639] = "GROUND" -- Exodar Elekk (new Argent draeni)
SJMount_staticMountList[36702] = "GROUND" -- Fiery Warhorse
SJMount_staticMountList[63643] = "GROUND" -- Forsaken Warhorse (new Argent undead)
SJMount_staticMountList[84751] = "GROUND" -- Fossilized Raptor
SJMount_staticMountList[23509] = "GROUND" -- Frostwolf Howler
SJMount_staticMountList[63638] = "GROUND" -- Gnomeregan Mechanostrider (new Argent gnome)
SJMount_staticMountList[87090] = "GROUND" -- Goblin Trike
SJMount_staticMountList[87091] = "GROUND" -- Goblin Turbo-Trike
SJMount_staticMountList[90621] = "GROUND" -- Golden King
SJMount_staticMountList[59810] = "GROUND" -- Grand Black War Mammoth
SJMount_staticMountList[59811] = "GROUND" -- Grand Black War Mammoth
SJMount_staticMountList[60136] = "GROUND" -- Grand Caravan Mammoth
SJMount_staticMountList[60140] = "GROUND" -- Grand Caravan Mammoth
SJMount_staticMountList[59802] = "GROUND" -- Grand Ice Mammoth
SJMount_staticMountList[59804] = "GROUND" -- Grand Ice Mammoth
SJMount_staticMountList[35710] = "GROUND" -- Gray Elekk
SJMount_staticMountList[18989] = "GROUND" -- Gray Kodo
SJMount_staticMountList[6777]  = "GROUND" -- Gray Ram
SJMount_staticMountList[459]   = "GROUND" -- Gray Wolf
SJMount_staticMountList[35713] = "GROUND" -- Great Blue Elekk
SJMount_staticMountList[49379] = "GROUND" -- Great Brewfest Kodo
SJMount_staticMountList[23249] = "GROUND" -- Great Brown Kodo
SJMount_staticMountList[34407] = "GROUND" -- Great Elite Elekk
SJMount_staticMountList[35712] = "GROUND" -- Great Green Elekk
SJMount_staticMountList[65641] = "GROUND" -- Great Golden Kodo (old Argent tauren)
SJMount_staticMountList[23248] = "GROUND" -- Great Gray Kodo
SJMount_staticMountList[35714] = "GROUND" -- Great Purple Elekk
SJMount_staticMountList[65637] = "GROUND" -- Great Red Elekk (old Argent draeni)
SJMount_staticMountList[69826] = "GROUND" -- Great Sunwalker Kodo
SJMount_staticMountList[23247] = "GROUND" -- Great White Kodo
SJMount_staticMountList[15780] = "GROUND" -- Green Mechanostrider
SJMount_staticMountList[17453] = "GROUND" -- Green Mechanostrider
SJMount_staticMountList[17465] = "GROUND" -- Green Skeletal Warhorse
SJMount_staticMountList[88750] = "GROUND" -- Grey Riding Camel
SJMount_staticMountList[16060] = "GROUND" -- Golden Sabercat *Unconfirmed*
SJMount_staticMountList[48025] = "GROUND" -- Headless Horseman's Horse (variable)
SJMount_staticMountList[59797] = "GROUND" -- Ice Mammoth
SJMount_staticMountList[59799] = "GROUND" -- Ice Mammoth
SJMount_staticMountList[63636] = "GROUND" -- Ironforge Ram (new Argent dwarf)
SJMount_staticMountList[93644] = "GROUND" -- Kor'kron Annihilator
SJMount_staticMountList[55531] = "GROUND" -- Mechano-Hog
SJMount_staticMountList[60424] = "GROUND" -- Mekgineer's Chopper
SJMount_staticMountList[66846] = "GROUND" -- Ochre Skeletal Warhorse
SJMount_staticMountList[63640] = "GROUND" -- Orgrimmar Wolf (new Argent orc)
SJMount_staticMountList[471]   = "GROUND" -- Palamino
SJMount_staticMountList[472]   = "GROUND" -- Pinto
SJMount_staticMountList[35711] = "GROUND" -- Purple Elekk
SJMount_staticMountList[35018] = "GROUND" -- Purple Hawkstrider
SJMount_staticMountList[17455] = "GROUND" -- Purple Mechanostrider
SJMount_staticMountList[23246] = "GROUND" -- Purple Skeletal Warhorse
SJMount_staticMountList[41252] = "GROUND" -- Raven Lord
SJMount_staticMountList[17456] = "GROUND" -- Red & Blue Mechanostrider
SJMount_staticMountList[34795] = "GROUND" -- Red Hawkstrider
SJMount_staticMountList[10873] = "GROUND" -- Red Mechanostrider
SJMount_staticMountList[17462] = "GROUND" -- Red Skeletal Horse
SJMount_staticMountList[22722] = "GROUND" -- Red Skeletal Warhorse
SJMount_staticMountList[30174] = "GROUND" -- Riding Turtle
SJMount_staticMountList[17481] = "GROUND" -- Rivendare's Deathcharger
SJMount_staticMountList[39317] = "GROUND" -- Silver Riding Talbuk
SJMount_staticMountList[34898] = "GROUND" -- Silver War Talbuk
SJMount_staticMountList[63642] = "GROUND" -- Silvermoon Hawkstrider (new Argent bloodelf)
SJMount_staticMountList[92231] = "GROUND" -- Spectral Steed
SJMount_staticMountList[42776] = "GROUND" -- Spectral Tiger
SJMount_staticMountList[92232] = "GROUND" -- Spectral Wolf
SJMount_staticMountList[10789] = "GROUND" -- Spotted Frostsaber
SJMount_staticMountList[15781] = "GROUND" -- Steel Mechanostrider
SJMount_staticMountList[23510] = "GROUND" -- Stormpike Battle Charger
SJMount_staticMountList[63232] = "GROUND" -- Stormwind Steed (new Argent human)
SJMount_staticMountList[8394]  = "GROUND" -- Striped Frostsaber
SJMount_staticMountList[10793] = "GROUND" -- Striped Nightsaber
SJMount_staticMountList[23214] = "GROUND" -- Summon Charger (Alliance Paladin)
SJMount_staticMountList[34767] = "GROUND" -- Summon Charger (Bloodelf Paladin)
SJMount_staticMountList[23161] = "GROUND" -- Summon Dreadsteed
SJMount_staticMountList[5784]  = "GROUND" -- Summon Felsteed
SJMount_staticMountList[34769] = "GROUND" -- Summon Warhorse (Bloodelf Paladin)
SJMount_staticMountList[13819] = "GROUND" -- Summon Warhorse (Alliance Paladin)
SJMount_staticMountList[66091] = "GROUND" -- Sunreaver Hawkstrider
SJMount_staticMountList[23241] = "GROUND" -- Swift Blue Raptor
SJMount_staticMountList[43900] = "GROUND" -- Swift Brewfest Ram
SJMount_staticMountList[23238] = "GROUND" -- Swift Brown Ram
SJMount_staticMountList[23229] = "GROUND" -- Swift Brown Steed
SJMount_staticMountList[23250] = "GROUND" -- Swift Brown Wolf
SJMount_staticMountList[65646] = "GROUND" -- Swift Burgundy Wolf (old Argent orc) (got off thottbot not positive if correct)
SJMount_staticMountList[23221] = "GROUND" -- Swift Frostsaber
SJMount_staticMountList[23239] = "GROUND" -- Swift Gray Ram
SJMount_staticMountList[65640] = "GROUND" -- Swift Gray Steed (old Argent human)
SJMount_staticMountList[23252] = "GROUND" -- Swift Gray Wolf
SJMount_staticMountList[35025] = "GROUND" -- Swift Green Hawkstrider
SJMount_staticMountList[23225] = "GROUND" -- Swift Green Mechanostrider
SJMount_staticMountList[23219] = "GROUND" -- Swift Mistsaber
SJMount_staticMountList[65638] = "GROUND" -- Swift Moonsaber (old Argent nightelf)
SJMount_staticMountList[23242] = "GROUND" -- Swift Olive Raptor
SJMount_staticMountList[23243] = "GROUND" -- Swift Orange Raptor
SJMount_staticMountList[23227] = "GROUND" -- Swift Palamino
SJMount_staticMountList[33660] = "GROUND" -- Swift Pink Hawkstrider
SJMount_staticMountList[35027] = "GROUND" -- Swift Purple Hawkstrider
SJMount_staticMountList[65644] = "GROUND" -- Swift Purple Raptor (old Argent troll)
SJMount_staticMountList[24242] = "GROUND" -- Swift Razzashi Raptor
SJMount_staticMountList[65639] = "GROUND" -- Swift Red Hawkstrider (old Argent bloodelf)
SJMount_staticMountList[42777] = "GROUND" -- Swift Spectral Tiger
SJMount_staticMountList[102349]= "GROUND" -- Swift Springstrider
SJMount_staticMountList[23338] = "GROUND" -- Swift Stormsaber
SJMount_staticMountList[23251] = "GROUND" -- Swift Timber Wolf
SJMount_staticMountList[65643] = "GROUND" -- Swift Violet Ram (old Argent dwarf)
SJMount_staticMountList[47037] = "GROUND" -- Swift War Elekk
SJMount_staticMountList[35028] = "GROUND" -- Swift Warstrider
SJMount_staticMountList[46628] = "GROUND" -- Swift White Hawkstrider
SJMount_staticMountList[23223] = "GROUND" -- Swift White Mechanostrider
SJMount_staticMountList[23240] = "GROUND" -- Swift White Ram
SJMount_staticMountList[23228] = "GROUND" -- Swift White Steed
SJMount_staticMountList[23222] = "GROUND" -- Swift Yellow Mechanostrider
SJMount_staticMountList[48954] = "GROUND" -- Swift Zhevra
SJMount_staticMountList[49322] = "GROUND" -- Swift Zhevra
SJMount_staticMountList[24252] = "GROUND" -- Swift Zulian Tiger
SJMount_staticMountList[88749] = "GROUND" -- Tan Riding Camel
SJMount_staticMountList[39318] = "GROUND" -- Tan Riding Talbuk
SJMount_staticMountList[34899] = "GROUND" -- Tan War Talbuk
SJMount_staticMountList[63641] = "GROUND" -- Thunder Bluff Kodo (new Argent tauren)
SJMount_staticMountList[580]   = "GROUND" -- Timber Wolf
SJMount_staticMountList[65642] = "GROUND" -- Turbostrider  (old Argent gnome) (got off thottbot not positive if correct)
SJMount_staticMountList[10796] = "GROUND" -- Turquoise Raptor
SJMount_staticMountList[92155] = "GROUND" -- Ultramarine Qiraji Battle Tank
SJMount_staticMountList[17454] = "GROUND" -- Unpainted Mechanostrider
SJMount_staticMountList[10799] = "GROUND" -- Violet Raptor
SJMount_staticMountList[54753] = "GROUND" -- White Polar Bear
SJMount_staticMountList[6898]  = "GROUND" -- White Ram
SJMount_staticMountList[39319] = "GROUND" -- White Riding Talbuk
SJMount_staticMountList[65645] = "GROUND" -- White Skeletal Warhorse (old Argent undead)
SJMount_staticMountList[468]   = "GROUND" -- White Stallion
SJMount_staticMountList[34897] = "GROUND" -- White War Talbuk
SJMount_staticMountList[581]   = "GROUND" -- Winter Wolf
SJMount_staticMountList[17229] = "GROUND" -- Winterspring Frostsaber
SJMount_staticMountList[59791] = "GROUND" -- Wooly Mammoth
SJMount_staticMountList[59793] = "GROUND" -- Wooly Mammoth
SJMount_staticMountList[74918] = "GROUND" -- Wooly White Rhino

-- -----------------------------------------------------------------------------
-- Flying Mounts (SJMOUNT_CONSTS.MOUNTLEVELS.MOUNTLEVEL2)
-- -----------------------------------------------------------------------------
SJMount_staticMountList[72286] = "FLYING" -- Invincible (variable)
SJMount_staticMountList[63796] = "FLYING" -- Mimiron's Head (310)
SJMount_staticMountList[71810] = "FLYING" -- Wrathful Gladiator's Frostwyrm (310)
SJMount_staticMountList[67336] = "FLYING" -- Relentless Gladiator's Frostwyrm (310)
SJMount_staticMountList[65439] = "FLYING" -- Furious Gladiator's Frostwyrm (310)
SJMount_staticMountList[64927] = "FLYING" -- Deadly Gladiator's Frostwyrm (310)
SJMount_staticMountList[72808] = "FLYING" -- Bloodbathed Frostbrood Vanquisher (310)
SJMount_staticMountList[43810] = "FLYING" -- Frost Wyrm (280) *Unconfirmed*
SJMount_staticMountList[51960] = "FLYING" -- Frost Wyrm (280) *Unconfirmed*
SJMount_staticMountList[63956] = "FLYING" -- Ironbound Proto Drake (310)
SJMount_staticMountList[63963] = "FLYING" -- Rusted Proto Drake (310)
SJMount_staticMountList[40192] = "FLYING" -- Ashes of Al'ar (Phoenix) (310)
SJMount_staticMountList[58615] = "FLYING" -- Brutal Nether Drake (310)
SJMount_staticMountList[44317] = "FLYING" -- Merciless Nether Drake (310)
SJMount_staticMountList[44744] = "FLYING" -- Merciless Nether Drake (310)
SJMount_staticMountList[37015] = "FLYING" -- Swift Nether Drake (310)
SJMount_staticMountList[49193] = "FLYING" -- Vengeful Nether Drake (310)
SJMount_staticMountList[60021] = "FLYING" -- Plagued Proto Drake (310)
SJMount_staticMountList[59976] = "FLYING" -- Black Proto Drake (310)
SJMount_staticMountList[59996] = "FLYING" -- Blue Proto Drake (280)
SJMount_staticMountList[61294] = "FLYING" -- Green Proto Drake (280)
SJMount_staticMountList[59961] = "FLYING" -- Red Proto Drake (280)
SJMount_staticMountList[60002] = "FLYING" -- Time-Lost Proto Drake (280)
SJMount_staticMountList[60024] = "FLYING" -- Violet Proto Drake (280)
SJMount_staticMountList[88335] = "FLYING" -- Drake of the East Wind (280)
SJMount_staticMountList[88742] = "FLYING" -- Drake of the North Wind (280)
SJMount_staticMountList[88744] = "FLYING" -- Drake of the South Wind (280)
SJMount_staticMountList[88741] = "FLYING" -- Drake of the West Wind (280)
SJMount_staticMountList[88990] = "FLYING" -- Dark Phoenix (280)
SJMount_staticMountList[88718] = "FLYING" -- Phosphorescent Stone Drake (280)
SJMount_staticMountList[93326] = "FLYING" -- Sandstone Drake (280)
SJMount_staticMountList[88746] = "FLYING" -- Vitreous Stone Drake (280)
SJMount_staticMountList[88331] = "FLYING" -- Volcanic Stone Drake (280)
SJMount_staticMountList[62048] = "FLYING" -- Black Dragonhawk Mount (280)
SJMount_staticMountList[61996] = "FLYING" -- Blue Dragonhawk Mount (280)
SJMount_staticMountList[61997] = "FLYING" -- Red Dragonhawk Mount (280)
SJMount_staticMountList[71342] = "FLYING" -- Big Love Rocket (variable)
SJMount_staticMountList[75596] = "FLYING" -- Frosty Flying Carpet (280)
SJMount_staticMountList[66087] = "FLYING" -- Silver Covenant Hippogryph (280)
SJMount_staticMountList[66088] = "FLYING" -- Sunreaver Dragonhawk (280)
SJMount_staticMountList[60025] = "FLYING" -- Albino Drake (280)
SJMount_staticMountList[59567] = "FLYING" -- Azure Drake (280)
SJMount_staticMountList[59650] = "FLYING" -- Black Drake (280)
SJMount_staticMountList[59568] = "FLYING" -- Blue Drake (280)
SJMount_staticMountList[59569] = "FLYING" -- Bronze Drake (280)
SJMount_staticMountList[59570] = "FLYING" -- Red Drake (280)
SJMount_staticMountList[59571] = "FLYING" -- Twilight Drake (280)
SJMount_staticMountList[63844] = "FLYING" -- Argent Hippogryph (280)
SJMount_staticMountList[41514] = "FLYING" -- Azure Netherwing Drake (280)
SJMount_staticMountList[41515] = "FLYING" -- Cobalt Netherwing Drake (280)
SJMount_staticMountList[41513] = "FLYING" -- Onyx Netherwing Drake (280)
SJMount_staticMountList[41516] = "FLYING" -- Purple Netherwing Drake (280)
SJMount_staticMountList[41517] = "FLYING" -- Veridian Netherwing Drake (280)
SJMount_staticMountList[41518] = "FLYING" -- Violet Netherwing Drake (280)
SJMount_staticMountList[39803] = "FLYING" -- Blue Riding Nether Ray (280)
SJMount_staticMountList[39798] = "FLYING" -- Green Riding Nether Ray (280)
SJMount_staticMountList[39801] = "FLYING" -- Purple Riding Nether Ray (280)
SJMount_staticMountList[39800] = "FLYING" -- Red Riding Nether Ray (280)
SJMount_staticMountList[39802] = "FLYING" -- Silver Riding Nether Ray (280)
SJMount_staticMountList[43927] = "FLYING" -- Cenarian War Hippogryph (280)
SJMount_staticMountList[63844] = "FLYING" -- Argent Hippogryph (280)
SJMount_staticMountList[61230] = "FLYING" -- Armored Blue Wind Rider (280)
SJMount_staticMountList[61229] = "FLYING" -- Armored Snowy Gryphon (280)
SJMount_staticMountList[61309] = "FLYING" -- Magnificient Flying Carpet (280)
SJMount_staticMountList[32242] = "FLYING" -- Swift Blue Gryphon (280)
SJMount_staticMountList[32290] = "FLYING" -- Swift Green Gryphon (280)
SJMount_staticMountList[32295] = "FLYING" -- Swift Green Wind Rider (280)
SJMount_staticMountList[61442] = "FLYING" -- Swift Mooncloth Carpet (280)
SJMount_staticMountList[32292] = "FLYING" -- Swift Purple Griffon (280)
SJMount_staticMountList[32297] = "FLYING" -- Swift Purple Wind Rider (280)
SJMount_staticMountList[32289] = "FLYING" -- Swift Red Gryphon (280)
SJMount_staticMountList[32246] = "FLYING" -- Swift Red Wind Rider (280)
SJMount_staticMountList[61444] = "FLYING" -- Swift Shadoweave Carpet (280)
SJMount_staticMountList[61446] = "FLYING" -- Swift Spellfire Carpet (280)
SJMount_staticMountList[32296] = "FLYING" -- Swift Yellow Wind Rider (280)
SJMount_staticMountList[44151] = "FLYING" -- Turbo-Charged Flying Machine (280)
SJMount_staticMountList[46199] = "FLYING" -- X-51 Nether-Rocket Extreme (280)
SJMount_staticMountList[54729] = "FLYING" -- Winged Steed of the Ebon Blade (variable)
SJMount_staticMountList[48025] = "FLYING" -- Headless Horseman's Horse (variable)
SJMount_staticMountList[75614] = "FLYING" -- Celestial Steed (variable)
SJMount_staticMountList[75973] = "FLYING" -- X-53 Touring Rocket (variable)
SJMount_staticMountList[40120] = "FLYING" -- Druid Swift Flight Form
SJMount_staticMountList[32243] = "FLYING" -- Tawny Wind Rider
SJMount_staticMountList[32244] = "FLYING" -- Blue Wind Rider
SJMount_staticMountList[32239] = "FLYING" -- Ebon Gryphon
SJMount_staticMountList[61451] = "FLYING" -- Flying Carpet
SJMount_staticMountList[44153] = "FLYING" -- Flying Machine
SJMount_staticMountList[32235] = "FLYING" -- Golden Gryphon
SJMount_staticMountList[32245] = "FLYING" -- Green Wind Rider
SJMount_staticMountList[32240] = "FLYING" -- Snowy Gryphon
SJMount_staticMountList[46197] = "FLYING" -- X-51 Nether-Rocket
SJMount_staticMountList[33943] = "FLYING" -- Druid Flight Form

-- -----------------------------------------------------------------------------
-- Water Mounts (SJMOUNT_CONSTS.MOUNTLEVELS.MOUNTLEVEL3)
-- -----------------------------------------------------------------------------
SJMount_staticMountList[64731] = "WATER" -- Sea Turtle
SJMount_staticMountList[75207] = "WATER" -- Abyssal Seahorse
