-- The mount lists for Useful Extras and QuickMountGather by EVmaker

SJMount_staticMountList = {}

--------------------------------------------------------------------------------
-- Epic Ground Mounts (SJMOUNT_LEVEL1)
--------------------------------------------------------------------------------
SJMount_staticMountList[92155] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Ultramarine Qiraji Battle Tank
SJMount_staticMountList[26656] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black Qiraji Battle Tank
SJMount_staticMountList[41252] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Raven Lord
SJMount_staticMountList[93644] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Kor'kron Annihilator
SJMount_staticMountList[90621] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Golden King
SJMount_staticMountList[92232] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Spectral Wolf
SJMount_staticMountList[92231] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Spectral Steed
SJMount_staticMountList[84751] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Fossilized Raptor
SJMount_staticMountList[43688] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Amani War Bear
SJMount_staticMountList[74918] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Wooly White Rhino
SJMount_staticMountList[58983] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Big Blizzard Bear
SJMount_staticMountList[42777] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Spectral Tiger
SJMount_staticMountList[24242] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Razzashi Raptor
SJMount_staticMountList[24252] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Zulian Tiger
SJMount_staticMountList[46628] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift White Hawkstrider
SJMount_staticMountList[48954] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Zhevra
SJMount_staticMountList[49322] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Zhevra
SJMount_staticMountList[69826] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Sunwalker Kodo
SJMount_staticMountList[68188] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Crusader's Black Warhorse
SJMount_staticMountList[68187] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Crusader's White Warhorse
SJMount_staticMountList[66906] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Argent Charger
SJMount_staticMountList[67466] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Argent Warhorse
SJMount_staticMountList[66091] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Sunreaver Hawkstrider
SJMount_staticMountList[73313] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Crimson Deathcharger
SJMount_staticMountList[48778] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Deathcharger
SJMount_staticMountList[16056] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Ancient Frostsaber (feat of strength)
SJMount_staticMountList[16055] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black Nightsaber (feat of strength)
SJMount_staticMountList[87091] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Goblin Turbo-Trike
SJMount_staticMountList[60114] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Armored Brown Bear
SJMount_staticMountList[60116] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Armored Brown Bear
SJMount_staticMountList[88748] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Brown Riding Camel
SJMount_staticMountList[88750] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Grey Riding Camel
SJMount_staticMountList[88749] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Tan Riding Camel
SJMount_staticMountList[51412] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Big Battle Bear
SJMount_staticMountList[22719] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black Battlestrider
SJMount_staticMountList[59572] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black Polar Bear
SJMount_staticMountList[17461] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black Ram
SJMount_staticMountList[60118] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Bear
SJMount_staticMountList[60119] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Bear
SJMount_staticMountList[48027] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Elekk
SJMount_staticMountList[22718] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Kodo
SJMount_staticMountList[59785] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Mammoth
SJMount_staticMountList[59788] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Mammoth
SJMount_staticMountList[22720] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Ram
SJMount_staticMountList[22721] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Raptor
SJMount_staticMountList[22717] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Steed
SJMount_staticMountList[22723] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Tiger
SJMount_staticMountList[22724] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Black War Wolf
SJMount_staticMountList[59573] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Brown Polar Bear
SJMount_staticMountList[39315] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Cobalt Riding Talbuk
SJMount_staticMountList[34896] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Cobalt War Talbuk
SJMount_staticMountList[39316] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Dark Riding Talbuk
SJMount_staticMountList[34790] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Dark War Talbuk
SJMount_staticMountList[36702] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Fiery Warhorse
SJMount_staticMountList[23509] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Frostwolf Howler
SJMount_staticMountList[59810] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Grand Black War Mammoth
SJMount_staticMountList[59811] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Grand Black War Mammoth
SJMount_staticMountList[60136] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Grand Caravan Mammoth
SJMount_staticMountList[60140] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Grand Caravan Mammoth
SJMount_staticMountList[59802] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Grand Ice Mammoth
SJMount_staticMountList[59804] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Grand Ice Mammoth
SJMount_staticMountList[35713] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Blue Elekk
SJMount_staticMountList[49379] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Brewfest Kodo
SJMount_staticMountList[23249] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Brown Kodo
SJMount_staticMountList[34407] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Elite Elekk
SJMount_staticMountList[23248] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Gray Kodo
SJMount_staticMountList[35712] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Green Elekk
SJMount_staticMountList[35714] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Purple Elekk
SJMount_staticMountList[23247] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great White Kodo
SJMount_staticMountList[17465] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Green Skeletal Warhorse
SJMount_staticMountList[48025] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Headless Horseman's Horse (variable)
SJMount_staticMountList[75614] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Celestial Steed (variable)
SJMount_staticMountList[59797] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Ice Mammoth
SJMount_staticMountList[59799] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Ice Mammoth
SJMount_staticMountList[55531] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Mechano-Hog
SJMount_staticMountList[60424] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Mekgineer's Chopper
SJMount_staticMountList[23246] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Purple Skeletal Warhorse
SJMount_staticMountList[22722] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Red Skeletal Warhorse
SJMount_staticMountList[17481] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Rivendare's Deathcharger
SJMount_staticMountList[39317] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Silver Riding Talbuk
SJMount_staticMountList[34898] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Silver War Talbuk
SJMount_staticMountList[23510] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Stormpike Battle Charger
SJMount_staticMountList[23241] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Blue Raptor
SJMount_staticMountList[43900] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Brewfest Ram
SJMount_staticMountList[23238] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Brown Ram
SJMount_staticMountList[23229] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Brown Steed
SJMount_staticMountList[23250] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Brown Wolf
SJMount_staticMountList[23221] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Frostsaber
SJMount_staticMountList[23239] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Gray Ram
SJMount_staticMountList[23252] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Gray Wolf
SJMount_staticMountList[35025] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Green Hawkstrider
SJMount_staticMountList[23225] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Green Mechanostrider
SJMount_staticMountList[23219] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Mistsaber
SJMount_staticMountList[23242] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Olive Raptor
SJMount_staticMountList[23243] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Orange Raptor
SJMount_staticMountList[23227] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Palamino
SJMount_staticMountList[33660] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Pink Hawkstrider
SJMount_staticMountList[35027] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Purple Hawkstrider
SJMount_staticMountList[23338] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Stormsaber
SJMount_staticMountList[23251] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Timber Wolf
SJMount_staticMountList[47037] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift War Elekk
SJMount_staticMountList[35028] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Warstrider
SJMount_staticMountList[23223] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift White Mechanostrider
SJMount_staticMountList[23240] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift White Ram
SJMount_staticMountList[23228] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift White Steed
SJMount_staticMountList[23222] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Yellow Mechanostrider
SJMount_staticMountList[39318] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Tan Riding Talbuk
SJMount_staticMountList[34899] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Tan War Talbuk
SJMount_staticMountList[54753] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- White Polar Bear
SJMount_staticMountList[39319] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- White Riding Talbuk
SJMount_staticMountList[34897] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- White War Talbuk
SJMount_staticMountList[17229] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Winterspring Frostsaber
SJMount_staticMountList[59791] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Wooly Mammoth
SJMount_staticMountList[59793] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Wooly Mammoth
SJMount_staticMountList[23214] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Summon Charger (Alliance Paladin)
SJMount_staticMountList[34767] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Summon Charger (Bloodelf Paladin)
SJMount_staticMountList[23161] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Summon Dreadsteed
SJMount_staticMountList[63635] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Darkspear Raptor (new Argent troll)
SJMount_staticMountList[65644] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Purple Raptor (old Argent troll)
SJMount_staticMountList[63643] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Forsaken Warhorse (new Argent undead)
SJMount_staticMountList[65645] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- White Skeletal Warhorse (old Argent undead)
SJMount_staticMountList[63641] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Thunder Bluff Kodo (new Argent tauren)
SJMount_staticMountList[65641] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Golden Kodo (old Argent tauren)
SJMount_staticMountList[63640] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Orgrimmar Wolf (new Argent orc)
SJMount_staticMountList[65646] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Burgundy Wolf (old Argent orc) (got off thottbot not positive if correct)
SJMount_staticMountList[63642] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Silvermoon Hawkstrider (new Argent bloodelf)
SJMount_staticMountList[65639] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Red Hawkstrider (old Argent bloodelf)
SJMount_staticMountList[63637] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Darnassian Nightsaber (new Argent nightelf)
SJMount_staticMountList[65638] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Moonsaber (old Argent nightelf)
SJMount_staticMountList[63639] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Exodar Elekk (new Argent draeni)
SJMount_staticMountList[65637] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Great Red Elekk (old Argent draeni)
SJMount_staticMountList[63638] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Gnomeregan Mechanostrider (new Argent gnome)
SJMount_staticMountList[65642] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Turbostrider  (old Argent gnome) (got off thottbot not positive if correct)
SJMount_staticMountList[63636] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Ironforge Ram (new Argent dwarf)
SJMount_staticMountList[65643] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Violet Ram (old Argent dwarf)
SJMount_staticMountList[63232] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Stormwind Steed (new Argent human)
SJMount_staticMountList[65640] = SJMOUNT_CONSTS.MOUNTLEVEL1 -- Swift Gray Steed (old Argent human)

--------------------------------------------------------------------------------
-- Regular Ground Mounts (SJMOUNT_LEVEL2)
--------------------------------------------------------------------------------
SJMount_staticMountList[66907] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Argent Warhorse
SJMount_staticMountList[87090] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Goblin Trike
SJMount_staticMountList[64977] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Black Skeletal Horse
SJMount_staticMountList[35020] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Blue Hawkstrider
SJMount_staticMountList[10969] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Blue Mechanostrider
SJMount_staticMountList[33630] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Blue Mechanostrider
SJMount_staticMountList[578]   = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Black Wolf
SJMount_staticMountList[64658] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Black Wolf
SJMount_staticMountList[6896]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Black Ram
SJMount_staticMountList[470]   = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Black Stallion
SJMount_staticMountList[35022] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Black Hawkstrider
SJMount_staticMountList[6897]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Blue Ram
SJMount_staticMountList[17463] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Blue Skeletal Horse
SJMount_staticMountList[50869] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brewfest Kodo
SJMount_staticMountList[49378] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brewfest Riding Kodo
SJMount_staticMountList[43899] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brewfest Ram
SJMount_staticMountList[50870] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brewfest Ram
SJMount_staticMountList[34406] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brown Elekk
SJMount_staticMountList[458]   = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brown Horse
SJMount_staticMountList[18990] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brown Kodo
SJMount_staticMountList[6899]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brown Ram
SJMount_staticMountList[17464] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brown Skeletal Horse
SJMount_staticMountList[6654]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Brown Wolf
SJMount_staticMountList[6648]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Chestnut Mare
SJMount_staticMountList[6653]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Dire Wolf
SJMount_staticMountList[8395]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Emerald Raptor
SJMount_staticMountList[16060] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Golden Sabercat *Unconfirmed*
SJMount_staticMountList[35710] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Gray Elekk
SJMount_staticMountList[18989] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Gray Kodo
SJMount_staticMountList[6777]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Gray Ram
SJMount_staticMountList[459]   = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Gray Wolf
SJMount_staticMountList[15780] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Green Mechanostrider
SJMount_staticMountList[17453] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Green Mechanostrider
SJMount_staticMountList[471]   = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Palamino
SJMount_staticMountList[472]   = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Pinto
SJMount_staticMountList[35711] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Purple Elekk
SJMount_staticMountList[35018] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Purple Hawkstrider
SJMount_staticMountList[17455] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Purple Mechanostrider
SJMount_staticMountList[17456] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Red & Blue Mechanostrider
SJMount_staticMountList[34795] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Red Hawkstrider
SJMount_staticMountList[10873] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Red Mechanostrider
SJMount_staticMountList[17462] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Red Skeletal Horse
SJMount_staticMountList[30174] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Riding Turtle
SJMount_staticMountList[42776] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Spectral Tiger
SJMount_staticMountList[10789] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Spotted Frostsaber
SJMount_staticMountList[15781] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Steel Mechanostrider
SJMount_staticMountList[8394]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Striped Frostsaber
SJMount_staticMountList[10793] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Striped Nightsaber
SJMount_staticMountList[580]   = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Timber Wolf
SJMount_staticMountList[10796] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Turquoise Raptor
SJMount_staticMountList[17454] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Unpainted Mechanostrider
SJMount_staticMountList[10799] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Violet Raptor
SJMount_staticMountList[6898]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- White Ram
SJMount_staticMountList[468]   = SJMOUNT_CONSTS.MOUNTLEVEL2 -- White Stallion
SJMount_staticMountList[581]   = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Winter Wolf
SJMount_staticMountList[34769] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Summon Warhorse (Bloodelf Paladin)
SJMount_staticMountList[13819] = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Summon Warhorse (Alliance Paladin)
SJMount_staticMountList[5784]  = SJMOUNT_CONSTS.MOUNTLEVEL2 -- Summon Felsteed

--------------------------------------------------------------------------------
-- Epic Flying Mounts (SJMOUNT_LEVEL3)
--------------------------------------------------------------------------------
SJMount_staticMountList[72286] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Invincible (variable)
SJMount_staticMountList[63796] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Mimiron's Head (310)
SJMount_staticMountList[71810] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Wrathful Gladiator's Frostwyrm (310)
SJMount_staticMountList[67336] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Relentless Gladiator's Frostwyrm (310)
SJMount_staticMountList[65439] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Furious Gladiator's Frostwyrm (310)
SJMount_staticMountList[64927] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Deadly Gladiator's Frostwyrm (310)
SJMount_staticMountList[72808] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Bloodbathed Frostbrood Vanquisher (310)
SJMount_staticMountList[43810] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Frost Wyrm (280) *Unconfirmed*
SJMount_staticMountList[51960] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Frost Wyrm (280) *Unconfirmed*
SJMount_staticMountList[63956] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Ironbound Proto Drake (310)
SJMount_staticMountList[63963] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Rusted Proto Drake (310)
SJMount_staticMountList[40192] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Ashes of Al'ar (Phoenix) (310)
SJMount_staticMountList[58615] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Brutal Nether Drake (310)
SJMount_staticMountList[44317] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Merciless Nether Drake (310)
SJMount_staticMountList[44744] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Merciless Nether Drake (310)
SJMount_staticMountList[37015] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Nether Drake (310)
SJMount_staticMountList[49193] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Vengeful Nether Drake (310)
SJMount_staticMountList[60021] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Plagued Proto Drake (310)
SJMount_staticMountList[59976] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Black Proto Drake (310)
SJMount_staticMountList[59996] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Blue Proto Drake (280)
SJMount_staticMountList[61294] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Green Proto Drake (280)
SJMount_staticMountList[59961] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Red Proto Drake (280)
SJMount_staticMountList[60002] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Time-Lost Proto Drake (280)
SJMount_staticMountList[60024] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Violet Proto Drake (280)
SJMount_staticMountList[88335] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Drake of the East Wind (280)
SJMount_staticMountList[88742] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Drake of the North Wind (280)
SJMount_staticMountList[88744] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Drake of the South Wind (280)
SJMount_staticMountList[88741] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Drake of the West Wind (280)
SJMount_staticMountList[88990] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Dark Phoenix (280)
SJMount_staticMountList[88718] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Phosphorescent Stone Drake (280)
SJMount_staticMountList[93326] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Sandstone Drake (280)
SJMount_staticMountList[88746] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Vitreous Stone Drake (280)
SJMount_staticMountList[88331] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Volcanic Stone Drake (280)
SJMount_staticMountList[62048] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Black Dragonhawk Mount (280)
SJMount_staticMountList[61996] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Blue Dragonhawk Mount (280)
SJMount_staticMountList[61997] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Red Dragonhawk Mount (280)
SJMount_staticMountList[71342] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Big Love Rocket (variable)
SJMount_staticMountList[75596] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Frosty Flying Carpet (280)
SJMount_staticMountList[66087] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Silver Covenant Hippogryph (280)
SJMount_staticMountList[66088] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Sunreaver Dragonhawk (280)
SJMount_staticMountList[60025] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Albino Drake (280)
SJMount_staticMountList[59567] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Azure Drake (280)
SJMount_staticMountList[59650] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Black Drake (280)
SJMount_staticMountList[59568] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Blue Drake (280)
SJMount_staticMountList[59569] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Bronze Drake (280)
SJMount_staticMountList[59570] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Red Drake (280)
SJMount_staticMountList[59571] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Twilight Drake (280)
SJMount_staticMountList[63844] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Argent Hippogryph (280)
SJMount_staticMountList[41514] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Azure Netherwing Drake (280)
SJMount_staticMountList[41515] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Cobalt Netherwing Drake (280)
SJMount_staticMountList[41513] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Onyx Netherwing Drake (280)
SJMount_staticMountList[41516] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Purple Netherwing Drake (280)
SJMount_staticMountList[41517] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Veridian Netherwing Drake (280)
SJMount_staticMountList[41518] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Violet Netherwing Drake (280)
SJMount_staticMountList[39803] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Blue Riding Nether Ray (280)
SJMount_staticMountList[39798] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Green Riding Nether Ray (280)
SJMount_staticMountList[39801] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Purple Riding Nether Ray (280)
SJMount_staticMountList[39800] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Red Riding Nether Ray (280)
SJMount_staticMountList[39802] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Silver Riding Nether Ray (280)
SJMount_staticMountList[43927] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Cenarian War Hippogryph (280)
SJMount_staticMountList[63844] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Argent Hippogryph (280)
SJMount_staticMountList[61230] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Armored Blue Wind Rider (280)
SJMount_staticMountList[61229] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Armored Snowy Gryphon (280)
SJMount_staticMountList[61309] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Magnificient Flying Carpet (280)
SJMount_staticMountList[32242] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Blue Gryphon (280)
SJMount_staticMountList[32290] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Green Gryphon (280)
SJMount_staticMountList[32295] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Green Wind Rider (280)
SJMount_staticMountList[61442] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Mooncloth Carpet (280)
SJMount_staticMountList[32292] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Purple Griffon (280)
SJMount_staticMountList[32297] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Purple Wind Rider (280)
SJMount_staticMountList[32289] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Red Gryphon (280)
SJMount_staticMountList[32246] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Red Wind Rider (280)
SJMount_staticMountList[61444] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Shadoweave Carpet (280)
SJMount_staticMountList[61446] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Spellfire Carpet (280)
SJMount_staticMountList[32296] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Swift Yellow Wind Rider (280)
SJMount_staticMountList[44151] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Turbo-Charged Flying Machine (280)
SJMount_staticMountList[46199] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- X-51 Nether-Rocket Extreme (280)
SJMount_staticMountList[54729] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Winged Steed of the Ebon Blade (variable)
SJMount_staticMountList[48025] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Headless Horseman's Horse (variable)
SJMount_staticMountList[75614] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Celestial Steed (variable)
SJMount_staticMountList[75973] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- X-53 Touring Rocket (variable)
SJMount_staticMountList[40120] = SJMOUNT_CONSTS.MOUNTLEVEL3 -- Druid Swift Flight Form

--------------------------------------------------------------------------------
-- Regular Flying Mounts (SJMOUNT_LEVEL4)
--------------------------------------------------------------------------------
SJMount_staticMountList[32243] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- Tawny Wind Rider
SJMount_staticMountList[32244] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- Blue Wind Rider
SJMount_staticMountList[32239] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- Ebon Gryphon
SJMount_staticMountList[61451] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- Flying Carpet
SJMount_staticMountList[44153] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- Flying Machine
SJMount_staticMountList[32235] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- Golden Gryphon
SJMount_staticMountList[32245] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- Green Wind Rider
SJMount_staticMountList[32240] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- Snowy Gryphon
SJMount_staticMountList[46197] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- X-51 Nether-Rocket
SJMount_staticMountList[33943] = SJMOUNT_CONSTS.MOUNTLEVEL4 -- Druid Flight Form

--------------------------------------------------------------------------------
-- Water Mounts (SJMOUNT_LEVEL5)
--------------------------------------------------------------------------------
SJMount_staticMountList[64731] = SJMOUNT_CONSTS.MOUNTLEVEL5 -- Sea Turtle
SJMount_staticMountList[75207] = SJMOUNT_CONSTS.MOUNTLEVEL5 -- Abyssal Seahorse