local T, C, L = unpack(select(2, ...))

-- -----------------------------------------------------------------------------
-- The mount lists for Useful Extras and QuickMountGather by EVmaker
-- -----------------------------------------------------------------------------

-- List of all mounts for reference
T.staticMountList = {}

-- Ground Mounts
T.staticMountList[98204] = "GROUND" -- Amani Battle Bear
T.staticMountList[43688] = "GROUND" -- Amani War Bear
T.staticMountList[16056] = "GROUND" -- Ancient Frostsaber (feat of strength)
T.staticMountList[66906] = "GROUND" -- Argent Charger
T.staticMountList[67466] = "GROUND" -- Argent Warhorse
T.staticMountList[66907] = "GROUND" -- Argent Warhorse
T.staticMountList[60114] = "GROUND" -- Armored Brown Bear
T.staticMountList[60116] = "GROUND" -- Armored Brown Bear
T.staticMountList[51412] = "GROUND" -- Big Battle Bear
T.staticMountList[58983] = "GROUND" -- Big Blizzard Bear
T.staticMountList[35020] = "GROUND" -- Blue Hawkstrider
T.staticMountList[10969] = "GROUND" -- Blue Mechanostrider
T.staticMountList[33630] = "GROUND" -- Blue Mechanostrider
T.staticMountList[22719] = "GROUND" -- Black Battlestrider
T.staticMountList[35022] = "GROUND" -- Black Hawkstrider
T.staticMountList[16055] = "GROUND" -- Black Nightsaber (feat of strength)
T.staticMountList[59572] = "GROUND" -- Black Polar Bear
T.staticMountList[26656] = "GROUND" -- Black Qiraji Battle Tank
T.staticMountList[17461] = "GROUND" -- Black Ram
T.staticMountList[64977] = "GROUND" -- Black Skeletal Horse
T.staticMountList[470]   = "GROUND" -- Black Stallion
T.staticMountList[60118] = "GROUND" -- Black War Bear
T.staticMountList[60119] = "GROUND" -- Black War Bear
T.staticMountList[48027] = "GROUND" -- Black War Elekk
T.staticMountList[22718] = "GROUND" -- Black War Kodo
T.staticMountList[59785] = "GROUND" -- Black War Mammoth
T.staticMountList[59788] = "GROUND" -- Black War Mammoth
T.staticMountList[22720] = "GROUND" -- Black War Ram
T.staticMountList[22721] = "GROUND" -- Black War Raptor
T.staticMountList[22717] = "GROUND" -- Black War Steed
T.staticMountList[22723] = "GROUND" -- Black War Tiger
T.staticMountList[22724] = "GROUND" -- Black War Wolf
T.staticMountList[578]   = "GROUND" -- Black Wolf
T.staticMountList[64658] = "GROUND" -- Black Wolf
T.staticMountList[6897]  = "GROUND" -- Blue Ram
T.staticMountList[17463] = "GROUND" -- Blue Skeletal Horse
T.staticMountList[50869] = "GROUND" -- Brewfest Kodo
T.staticMountList[49378] = "GROUND" -- Brewfest Riding Kodo
T.staticMountList[43899] = "GROUND" -- Brewfest Ram
T.staticMountList[50870] = "GROUND" -- Brewfest Ram
T.staticMountList[34406] = "GROUND" -- Brown Elekk
T.staticMountList[458]   = "GROUND" -- Brown Horse
T.staticMountList[18990] = "GROUND" -- Brown Kodo
T.staticMountList[59573] = "GROUND" -- Brown Polar Bear
T.staticMountList[6899]  = "GROUND" -- Brown Ram
T.staticMountList[88748] = "GROUND" -- Brown Riding Camel
T.staticMountList[17464] = "GROUND" -- Brown Skeletal Horse
T.staticMountList[6654]  = "GROUND" -- Brown Wolf
T.staticMountList[75614] = "GROUND" -- Celestial Steed (variable)
T.staticMountList[6648]  = "GROUND" -- Chestnut Mare
T.staticMountList[39315] = "GROUND" -- Cobalt Riding Talbuk
T.staticMountList[34896] = "GROUND" -- Cobalt War Talbuk
T.staticMountList[73313] = "GROUND" -- Crimson Deathcharger
T.staticMountList[68188] = "GROUND" -- Crusader's Black Warhorse
T.staticMountList[68187] = "GROUND" -- Crusader's White Warhorse
T.staticMountList[39316] = "GROUND" -- Dark Riding Talbuk
T.staticMountList[34790] = "GROUND" -- Dark War Talbuk
T.staticMountList[63635] = "GROUND" -- Darkspear Raptor (new Argent troll)
T.staticMountList[63637] = "GROUND" -- Darnassian Nightsaber (new Argent nightelf)
T.staticMountList[48778] = "GROUND" -- Deathcharger
T.staticMountList[6653]  = "GROUND" -- Dire Wolf
T.staticMountList[8395]  = "GROUND" -- Emerald Raptor
T.staticMountList[63639] = "GROUND" -- Exodar Elekk (new Argent draeni)
T.staticMountList[36702] = "GROUND" -- Fiery Warhorse
T.staticMountList[63643] = "GROUND" -- Forsaken Warhorse (new Argent undead)
T.staticMountList[84751] = "GROUND" -- Fossilized Raptor
T.staticMountList[23509] = "GROUND" -- Frostwolf Howler
T.staticMountList[63638] = "GROUND" -- Gnomeregan Mechanostrider (new Argent gnome)
T.staticMountList[87090] = "GROUND" -- Goblin Trike
T.staticMountList[87091] = "GROUND" -- Goblin Turbo-Trike
T.staticMountList[90621] = "GROUND" -- Golden King
T.staticMountList[59810] = "GROUND" -- Grand Black War Mammoth
T.staticMountList[59811] = "GROUND" -- Grand Black War Mammoth
T.staticMountList[60136] = "GROUND" -- Grand Caravan Mammoth
T.staticMountList[60140] = "GROUND" -- Grand Caravan Mammoth
T.staticMountList[59802] = "GROUND" -- Grand Ice Mammoth
T.staticMountList[59804] = "GROUND" -- Grand Ice Mammoth
T.staticMountList[35710] = "GROUND" -- Gray Elekk
T.staticMountList[18989] = "GROUND" -- Gray Kodo
T.staticMountList[6777]  = "GROUND" -- Gray Ram
T.staticMountList[459]   = "GROUND" -- Gray Wolf
T.staticMountList[35713] = "GROUND" -- Great Blue Elekk
T.staticMountList[49379] = "GROUND" -- Great Brewfest Kodo
T.staticMountList[23249] = "GROUND" -- Great Brown Kodo
T.staticMountList[34407] = "GROUND" -- Great Elite Elekk
T.staticMountList[35712] = "GROUND" -- Great Green Elekk
T.staticMountList[65641] = "GROUND" -- Great Golden Kodo (old Argent tauren)
T.staticMountList[23248] = "GROUND" -- Great Gray Kodo
T.staticMountList[35714] = "GROUND" -- Great Purple Elekk
T.staticMountList[65637] = "GROUND" -- Great Red Elekk (old Argent draeni)
T.staticMountList[69826] = "GROUND" -- Great Sunwalker Kodo
T.staticMountList[23247] = "GROUND" -- Great White Kodo
T.staticMountList[15780] = "GROUND" -- Green Mechanostrider
T.staticMountList[17453] = "GROUND" -- Green Mechanostrider
T.staticMountList[17465] = "GROUND" -- Green Skeletal Warhorse
T.staticMountList[88750] = "GROUND" -- Grey Riding Camel
T.staticMountList[16060] = "GROUND" -- Golden Sabercat *Unconfirmed*
T.staticMountList[48025] = "GROUND" -- Headless Horseman's Horse (variable)
T.staticMountList[59797] = "GROUND" -- Ice Mammoth
T.staticMountList[59799] = "GROUND" -- Ice Mammoth
T.staticMountList[63636] = "GROUND" -- Ironforge Ram (new Argent dwarf)
T.staticMountList[93644] = "GROUND" -- Kor'kron Annihilator
T.staticMountList[55531] = "GROUND" -- Mechano-Hog
T.staticMountList[60424] = "GROUND" -- Mekgineer's Chopper
T.staticMountList[66846] = "GROUND" -- Ochre Skeletal Warhorse
T.staticMountList[63640] = "GROUND" -- Orgrimmar Wolf (new Argent orc)
T.staticMountList[471]   = "GROUND" -- Palamino
T.staticMountList[472]   = "GROUND" -- Pinto
T.staticMountList[35711] = "GROUND" -- Purple Elekk
T.staticMountList[35018] = "GROUND" -- Purple Hawkstrider
T.staticMountList[17455] = "GROUND" -- Purple Mechanostrider
T.staticMountList[23246] = "GROUND" -- Purple Skeletal Warhorse
T.staticMountList[41252] = "GROUND" -- Raven Lord
T.staticMountList[17456] = "GROUND" -- Red & Blue Mechanostrider
T.staticMountList[34795] = "GROUND" -- Red Hawkstrider
T.staticMountList[10873] = "GROUND" -- Red Mechanostrider
T.staticMountList[17462] = "GROUND" -- Red Skeletal Horse
T.staticMountList[22722] = "GROUND" -- Red Skeletal Warhorse
T.staticMountList[30174] = "GROUND" -- Riding Turtle
T.staticMountList[17481] = "GROUND" -- Rivendare's Deathcharger
T.staticMountList[39317] = "GROUND" -- Silver Riding Talbuk
T.staticMountList[34898] = "GROUND" -- Silver War Talbuk
T.staticMountList[63642] = "GROUND" -- Silvermoon Hawkstrider (new Argent bloodelf)
T.staticMountList[92231] = "GROUND" -- Spectral Steed
T.staticMountList[42776] = "GROUND" -- Spectral Tiger
T.staticMountList[92232] = "GROUND" -- Spectral Wolf
T.staticMountList[10789] = "GROUND" -- Spotted Frostsaber
T.staticMountList[15781] = "GROUND" -- Steel Mechanostrider
T.staticMountList[23510] = "GROUND" -- Stormpike Battle Charger
T.staticMountList[63232] = "GROUND" -- Stormwind Steed (new Argent human)
T.staticMountList[8394]  = "GROUND" -- Striped Frostsaber
T.staticMountList[10793] = "GROUND" -- Striped Nightsaber
T.staticMountList[23214] = "GROUND" -- Summon Charger (Alliance Paladin)
T.staticMountList[34767] = "GROUND" -- Summon Charger (Bloodelf Paladin)
T.staticMountList[23161] = "GROUND" -- Summon Dreadsteed
T.staticMountList[5784]  = "GROUND" -- Summon Felsteed
T.staticMountList[34769] = "GROUND" -- Summon Warhorse (Bloodelf Paladin)
T.staticMountList[13819] = "GROUND" -- Summon Warhorse (Alliance Paladin)
T.staticMountList[66091] = "GROUND" -- Sunreaver Hawkstrider
T.staticMountList[23241] = "GROUND" -- Swift Blue Raptor
T.staticMountList[43900] = "GROUND" -- Swift Brewfest Ram
T.staticMountList[23238] = "GROUND" -- Swift Brown Ram
T.staticMountList[23229] = "GROUND" -- Swift Brown Steed
T.staticMountList[23250] = "GROUND" -- Swift Brown Wolf
T.staticMountList[65646] = "GROUND" -- Swift Burgundy Wolf (old Argent orc) (got off thottbot not positive if correct)
T.staticMountList[23221] = "GROUND" -- Swift Frostsaber
T.staticMountList[23239] = "GROUND" -- Swift Gray Ram
T.staticMountList[65640] = "GROUND" -- Swift Gray Steed (old Argent human)
T.staticMountList[23252] = "GROUND" -- Swift Gray Wolf
T.staticMountList[35025] = "GROUND" -- Swift Green Hawkstrider
T.staticMountList[23225] = "GROUND" -- Swift Green Mechanostrider
T.staticMountList[23219] = "GROUND" -- Swift Mistsaber
T.staticMountList[65638] = "GROUND" -- Swift Moonsaber (old Argent nightelf)
T.staticMountList[23242] = "GROUND" -- Swift Olive Raptor
T.staticMountList[23243] = "GROUND" -- Swift Orange Raptor
T.staticMountList[23227] = "GROUND" -- Swift Palamino
T.staticMountList[33660] = "GROUND" -- Swift Pink Hawkstrider
T.staticMountList[35027] = "GROUND" -- Swift Purple Hawkstrider
T.staticMountList[65644] = "GROUND" -- Swift Purple Raptor (old Argent troll)
T.staticMountList[24242] = "GROUND" -- Swift Razzashi Raptor
T.staticMountList[65639] = "GROUND" -- Swift Red Hawkstrider (old Argent bloodelf)
T.staticMountList[42777] = "GROUND" -- Swift Spectral Tiger
T.staticMountList[102349]= "GROUND" -- Swift Springstrider
T.staticMountList[23338] = "GROUND" -- Swift Stormsaber
T.staticMountList[23251] = "GROUND" -- Swift Timber Wolf
T.staticMountList[65643] = "GROUND" -- Swift Violet Ram (old Argent dwarf)
T.staticMountList[47037] = "GROUND" -- Swift War Elekk
T.staticMountList[35028] = "GROUND" -- Swift Warstrider
T.staticMountList[46628] = "GROUND" -- Swift White Hawkstrider
T.staticMountList[23223] = "GROUND" -- Swift White Mechanostrider
T.staticMountList[23240] = "GROUND" -- Swift White Ram
T.staticMountList[23228] = "GROUND" -- Swift White Steed
T.staticMountList[23222] = "GROUND" -- Swift Yellow Mechanostrider
T.staticMountList[48954] = "GROUND" -- Swift Zhevra
T.staticMountList[49322] = "GROUND" -- Swift Zhevra
T.staticMountList[24252] = "GROUND" -- Swift Zulian Tiger
T.staticMountList[88749] = "GROUND" -- Tan Riding Camel
T.staticMountList[39318] = "GROUND" -- Tan Riding Talbuk
T.staticMountList[34899] = "GROUND" -- Tan War Talbuk
T.staticMountList[63641] = "GROUND" -- Thunder Bluff Kodo (new Argent tauren)
T.staticMountList[580]   = "GROUND" -- Timber Wolf
T.staticMountList[65642] = "GROUND" -- Turbostrider  (old Argent gnome) (got off thottbot not positive if correct)
T.staticMountList[10796] = "GROUND" -- Turquoise Raptor
T.staticMountList[92155] = "GROUND" -- Ultramarine Qiraji Battle Tank
T.staticMountList[17454] = "GROUND" -- Unpainted Mechanostrider
T.staticMountList[10799] = "GROUND" -- Violet Raptor
T.staticMountList[54753] = "GROUND" -- White Polar Bear
T.staticMountList[6898]  = "GROUND" -- White Ram
T.staticMountList[39319] = "GROUND" -- White Riding Talbuk
T.staticMountList[65645] = "GROUND" -- White Skeletal Warhorse (old Argent undead)
T.staticMountList[468]   = "GROUND" -- White Stallion
T.staticMountList[34897] = "GROUND" -- White War Talbuk
T.staticMountList[581]   = "GROUND" -- Winter Wolf
T.staticMountList[17229] = "GROUND" -- Winterspring Frostsaber
T.staticMountList[59791] = "GROUND" -- Wooly Mammoth
T.staticMountList[59793] = "GROUND" -- Wooly Mammoth
T.staticMountList[74918] = "GROUND" -- Wooly White Rhino

-- Flying Mounts
T.staticMountList[72286] = "FLYING" -- Invincible (variable)
T.staticMountList[63796] = "FLYING" -- Mimiron's Head (310)
T.staticMountList[71810] = "FLYING" -- Wrathful Gladiator's Frostwyrm (310)
T.staticMountList[67336] = "FLYING" -- Relentless Gladiator's Frostwyrm (310)
T.staticMountList[65439] = "FLYING" -- Furious Gladiator's Frostwyrm (310)
T.staticMountList[64927] = "FLYING" -- Deadly Gladiator's Frostwyrm (310)
T.staticMountList[72808] = "FLYING" -- Bloodbathed Frostbrood Vanquisher (310)
T.staticMountList[43810] = "FLYING" -- Frost Wyrm (280) *Unconfirmed*
T.staticMountList[51960] = "FLYING" -- Frost Wyrm (280) *Unconfirmed*
T.staticMountList[63956] = "FLYING" -- Ironbound Proto Drake (310)
T.staticMountList[63963] = "FLYING" -- Rusted Proto Drake (310)
T.staticMountList[40192] = "FLYING" -- Ashes of Al'ar (Phoenix) (310)
T.staticMountList[58615] = "FLYING" -- Brutal Nether Drake (310)
T.staticMountList[44317] = "FLYING" -- Merciless Nether Drake (310)
T.staticMountList[44744] = "FLYING" -- Merciless Nether Drake (310)
T.staticMountList[37015] = "FLYING" -- Swift Nether Drake (310)
T.staticMountList[49193] = "FLYING" -- Vengeful Nether Drake (310)
T.staticMountList[60021] = "FLYING" -- Plagued Proto Drake (310)
T.staticMountList[59976] = "FLYING" -- Black Proto Drake (310)
T.staticMountList[59996] = "FLYING" -- Blue Proto Drake (280)
T.staticMountList[61294] = "FLYING" -- Green Proto Drake (280)
T.staticMountList[59961] = "FLYING" -- Red Proto Drake (280)
T.staticMountList[60002] = "FLYING" -- Time-Lost Proto Drake (280)
T.staticMountList[60024] = "FLYING" -- Violet Proto Drake (280)
T.staticMountList[88335] = "FLYING" -- Drake of the East Wind (280)
T.staticMountList[88742] = "FLYING" -- Drake of the North Wind (280)
T.staticMountList[88744] = "FLYING" -- Drake of the South Wind (280)
T.staticMountList[88741] = "FLYING" -- Drake of the West Wind (280)
T.staticMountList[88990] = "FLYING" -- Dark Phoenix (280)
T.staticMountList[88718] = "FLYING" -- Phosphorescent Stone Drake (280)
T.staticMountList[93326] = "FLYING" -- Sandstone Drake (280)
T.staticMountList[88746] = "FLYING" -- Vitreous Stone Drake (280)
T.staticMountList[88331] = "FLYING" -- Volcanic Stone Drake (280)
T.staticMountList[62048] = "FLYING" -- Black Dragonhawk Mount (280)
T.staticMountList[61996] = "FLYING" -- Blue Dragonhawk Mount (280)
T.staticMountList[61997] = "FLYING" -- Red Dragonhawk Mount (280)
T.staticMountList[71342] = "FLYING" -- Big Love Rocket (variable)
T.staticMountList[75596] = "FLYING" -- Frosty Flying Carpet (280)
T.staticMountList[66087] = "FLYING" -- Silver Covenant Hippogryph (280)
T.staticMountList[66088] = "FLYING" -- Sunreaver Dragonhawk (280)
T.staticMountList[60025] = "FLYING" -- Albino Drake (280)
T.staticMountList[59567] = "FLYING" -- Azure Drake (280)
T.staticMountList[59650] = "FLYING" -- Black Drake (280)
T.staticMountList[59568] = "FLYING" -- Blue Drake (280)
T.staticMountList[59569] = "FLYING" -- Bronze Drake (280)
T.staticMountList[59570] = "FLYING" -- Red Drake (280)
T.staticMountList[59571] = "FLYING" -- Twilight Drake (280)
T.staticMountList[63844] = "FLYING" -- Argent Hippogryph (280)
T.staticMountList[41514] = "FLYING" -- Azure Netherwing Drake (280)
T.staticMountList[41515] = "FLYING" -- Cobalt Netherwing Drake (280)
T.staticMountList[41513] = "FLYING" -- Onyx Netherwing Drake (280)
T.staticMountList[41516] = "FLYING" -- Purple Netherwing Drake (280)
T.staticMountList[41517] = "FLYING" -- Veridian Netherwing Drake (280)
T.staticMountList[41518] = "FLYING" -- Violet Netherwing Drake (280)
T.staticMountList[39803] = "FLYING" -- Blue Riding Nether Ray (280)
T.staticMountList[39798] = "FLYING" -- Green Riding Nether Ray (280)
T.staticMountList[39801] = "FLYING" -- Purple Riding Nether Ray (280)
T.staticMountList[39800] = "FLYING" -- Red Riding Nether Ray (280)
T.staticMountList[39802] = "FLYING" -- Silver Riding Nether Ray (280)
T.staticMountList[43927] = "FLYING" -- Cenarian War Hippogryph (280)
T.staticMountList[63844] = "FLYING" -- Argent Hippogryph (280)
T.staticMountList[61230] = "FLYING" -- Armored Blue Wind Rider (280)
T.staticMountList[61229] = "FLYING" -- Armored Snowy Gryphon (280)
T.staticMountList[61309] = "FLYING" -- Magnificient Flying Carpet (280)
T.staticMountList[32242] = "FLYING" -- Swift Blue Gryphon (280)
T.staticMountList[32290] = "FLYING" -- Swift Green Gryphon (280)
T.staticMountList[32295] = "FLYING" -- Swift Green Wind Rider (280)
T.staticMountList[61442] = "FLYING" -- Swift Mooncloth Carpet (280)
T.staticMountList[32292] = "FLYING" -- Swift Purple Griffon (280)
T.staticMountList[32297] = "FLYING" -- Swift Purple Wind Rider (280)
T.staticMountList[32289] = "FLYING" -- Swift Red Gryphon (280)
T.staticMountList[32246] = "FLYING" -- Swift Red Wind Rider (280)
T.staticMountList[61444] = "FLYING" -- Swift Shadoweave Carpet (280)
T.staticMountList[61446] = "FLYING" -- Swift Spellfire Carpet (280)
T.staticMountList[32296] = "FLYING" -- Swift Yellow Wind Rider (280)
T.staticMountList[44151] = "FLYING" -- Turbo-Charged Flying Machine (280)
T.staticMountList[46199] = "FLYING" -- X-51 Nether-Rocket Extreme (280)
T.staticMountList[54729] = "FLYING" -- Winged Steed of the Ebon Blade (variable)
T.staticMountList[48025] = "FLYING" -- Headless Horseman's Horse (variable)
T.staticMountList[75614] = "FLYING" -- Celestial Steed (variable)
T.staticMountList[75973] = "FLYING" -- X-53 Touring Rocket (variable)
T.staticMountList[40120] = "FLYING" -- Druid Swift Flight Form
T.staticMountList[32243] = "FLYING" -- Tawny Wind Rider
T.staticMountList[32244] = "FLYING" -- Blue Wind Rider
T.staticMountList[32239] = "FLYING" -- Ebon Gryphon
T.staticMountList[61451] = "FLYING" -- Flying Carpet
T.staticMountList[44153] = "FLYING" -- Flying Machine
T.staticMountList[32235] = "FLYING" -- Golden Gryphon
T.staticMountList[32245] = "FLYING" -- Green Wind Rider
T.staticMountList[32240] = "FLYING" -- Snowy Gryphon
T.staticMountList[46197] = "FLYING" -- X-51 Nether-Rocket
T.staticMountList[33943] = "FLYING" -- Druid Flight Form

-- Water Mounts
T.staticMountList[64731] = "WATER" -- Sea Turtle
T.staticMountList[75207] = "WATER" -- Abyssal Seahorse
